include:
- ./func/*
kind: ArchiveUploadSpec
name: func-mdHW

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: identifier-data-fn-fd9a0540-0b79-4ac0-80ec-27ad9a3a3dad
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: identifier-data-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-mdHW
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-20T03:35:08Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: identifier-data-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: identifier-data-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.user_identifier_data
    packageref:
      name: identifier-data-fn-fd9a0540-0b79-4ac0-80ec-27ad9a3a3dad
      namespace: default
  requestsPerPod: 1
  resources: {}
