include:
- ./func/*
kind: ArchiveUploadSpec
name: func-U4Pt

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: identifier-data-fn-783948d0-1fe5-4792-9116-5c638a133d92
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: identifier-data-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-U4Pt
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-08-25T17:25:20Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: identifier-data-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: identifier-data-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.user_identifier_data
    packageref:
      name: identifier-data-fn-783948d0-1fe5-4792-9116-5c638a133d92
      namespace: default
  requestsPerPod: 1
  resources: {}
