apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: identifier-data-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: identifier-data-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /onboarding/identifier_data
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /onboarding/identifier_data
