include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-BiQj

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onb-br-identifier-fn-a6d5a8fd-a21b-4999-b265-7ecd68abca19
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-BiQj
  environment:
    name: onb-br-identifier-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-05T17:20:25Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onb-br-identifier-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
      hpaMetrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
    StrategyType: execution
  concurrency: 500
  environment:
    name: onb-br-identifier-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: onb-br-identifier-fn-a6d5a8fd-a21b-4999-b265-7ecd68abca19
      namespace: default
  requestsPerPod: 10000
  resources: {}
